---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gatekeeper-system

resources:
  - ../../base/gatekeeper
  - ../../base/policies/disallow-http
  - ../../base/policies/verify-etcd-encryption

patches:
  - path: ../../patches/enforcement.yaml
    target:
      group: constraints.gatekeeper.sh
      version: v1beta1
      name: ingress-https-only
      kind: K8sHttpsOnly