---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gatekeeper-system

resources:
  - ../../base/gatekeeper
  - ../../base/policies/disallow-http
  - ../../base/policies/verify-etcd-encryption

components:
  - ../../components/gatekeeper-enforce-http-policy
  