---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/core/namespaces/etcd-backup
  - ../../base/core/namespaces/openshift-gatekeeper-system
  - ../../base/rbac.authorization.k8s.io/clusterrolebindings/etcd-backuper
  - ../../base/operators.coreos.com/subscriptions/gatekeeper